In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [3]:
adult = pd.read_csv('C:\\Users\\hp\\Jupyter Notebook Projects\\Sheik Dawood ML Projects\\adult.csv')
adult.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,#NAME?,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   object
 1   workclass       5000 non-null   object
 2   fnlwgt          5000 non-null   object
 3   education       5000 non-null   object
 4   education_num   5000 non-null   object
 5   marital_status  5000 non-null   object
 6   occupation      5000 non-null   object
 7   relationship    5000 non-null   object
 8   race            5000 non-null   object
 9   sex             5000 non-null   object
 10  capital_gain    5000 non-null   int64
 11  capital_loss    5000 non-null   int64
 12  hours_per_week  5000 non-null   int64
 13  native_country  5000 non-null   object
 14  income          5000 non-null   object
dtypes: int64(3), object(12)
memory usage: 586.1+ KB

In [6]:
adult.dtypes

age               object
workclass         object
fnlwgt            object
education         object
education_num     object
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [7]:
adult.describe()

       capital_gain  capital_loss  hours_per_week
count   5000.000000   5000.000000     5000.000000
mean    1033.640200     93.696800       40.519000
std     7051.802077    410.801418       12.109193
min        0.000000      0.000000        1.000000
25%        0.000000      0.000000       40.000000
50%        0.000000      0.000000       40.000000
75%        0.000000      0.000000       45.000000
max    99999.000000   2547.000000       99.000000

In [8]:
adult.workclass.value_counts()

Private             3435
Self-emp-not-inc     383
?                    331
Local-gov            329
State-gov            193
Self-emp-inc         182
Federal-gov          146
Without-pay            1
Name: workclass, dtype: int64

In [9]:
adult.education_num.value_counts()

9         1597
10        1114
13         819
14         251
11         215
7          198
12         163
6          144
4           98
15          88
5           74
#NAME?      57
8           55
16          55
3           43
2           22
1            7
Name: education_num, dtype: int64

In [10]:
adult.marital_status.value_counts()

Married-civ-spouse       2270
Never-married            1659
Divorced                  682
Widowed                   160
Separated                 158
Married-spouse-absent      66
Married-AF-spouse           5
Name: marital_status, dtype: int64

In [11]:
adult.occupation.value_counts()

Prof-specialty       625
Craft-repair         619
Exec-managerial      618
Sales                588
Adm-clerical         576
Other-service        495
?                    331
Machine-op-inspct    312
Transport-moving     247
Handlers-cleaners    196
Farming-fishing      143
Tech-support         140
Protective-serv       90
Priv-house-serv       18
Armed-Forces           2
Name: occupation, dtype: int64

In [12]:

adult.race.value_counts()

White                 4021
Black                  493
#NAME?                 264
Asian-Pac-Islander     145
Amer-Indian-Eskimo      48
Other                   29
Name: race, dtype: int64

In [13]:
adult.sex.value_counts()

Male      3332
Female    1621
#NAME?      47
Name: sex, dtype: int64

In [31]:
print(adult.native_country.value_counts())

United-States                 4465
Mexico                         104
?                               97
Canada                          28
Germany                         22
Philippines                     22
El-Salvador                     16
Puerto-Rico                     16
England                         16
Jamaica                         15
China                           15
Cuba                            14
Dominican-Republic              13
India                           12
Italy                           12
Iran                            11
Vietnam                         10
Taiwan                          10
Guatemala                       10
South                            9
Japan                            9
Poland                           9
Portugal                         7
Greece                           6
Haiti                            6
Nicaragua                        5
Columbia                         5
Cambodia                         4
Trinadad&Tobago                  4
Ecuador                          4
Ireland                          4
Honduras                         3
France                           3
Peru                             3
Outlying-US(Guam-USVI-etc)       3
Thailand                         2
Yugoslavia                       2
Laos                             2
Hong                             1
Scotland                         1
Name: native_country, dtype: int64

In [32]:
adult_ed=adult.drop('education',axis=1)
adult_ed.loc[(adult_ed.age=='#NAME?'),'age'] = np.nan
adult_ed.loc[(adult_ed.workclass=='?'),'workclass'] = np.nan
adult_ed.loc[(adult_ed.education_num=='#NAME?'),'education_num'] = np.nan
adult_ed.loc[(adult_ed.occupation=='?'),'occupation'] = np.nan
adult_ed.loc[(adult_ed.education_num=='?'),'education_num'] = np.nan
adult_ed.loc[(adult_ed.race=='#NAME?'),'race'] = np.nan

adult_ed.loc[(adult_ed.sex=='#NAME?'),'sex'] = np.nan
adult_ed.loc[(adult_ed.native_country=='?'),'native_country'] = np.nan
adult_ed.loc[(adult_ed.fnlwgt=='#NAME?'),'fnlwgt'] = np.nan

In [33]:
adult_ed['age'] = adult_ed['age'].fillna(adult_ed['age'].mode()[0])
adult_ed['workclass'] = adult_ed['workclass'].fillna(adult_ed['workclass'].mode()[0])
adult_ed['education_num'] = adult_ed['education_num'].fillna(adult_ed['education_num'].mode()[0])
adult_ed['occupation'] = adult_ed['occupation'].fillna(adult_ed['occupation'].mode()[0])
adult_ed['education_num'] = adult_ed['education_num'].fillna(adult_ed['education_num'].mode()[0])
adult_ed['race'] = adult_ed['race'].fillna(adult_ed['race'].mode()[0])

adult_ed['sex'] = adult_ed['sex'].fillna(adult_ed['sex'].mode()[0])
adult_ed['native_country'] = adult_ed['native_country'].fillna(adult_ed['native_country'].mode()[0])
adult_ed['fnlwgt'] = adult_ed['fnlwgt'].fillna(adult_ed['fnlwgt'].mode()[0])

In [34]:
adult_ed.head(20)

,age,workclass,fnlwgt,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,United-States,>50K
15,34,Private,245487,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,31,Self-emp-not-inc,123983,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K

In [35]:
adult_ed.age=adult_ed.age.astype('int64')
adult_ed.fnlwgt=adult_ed.fnlwgt.astype('int64')
adult_ed.education_num=adult_ed.education_num.astype('int64')

In [36]:
adult_ed.dtypes

age                int64
workclass         object
fnlwgt             int64
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [37]:

adult_ed['income_target']=np.where(adult_ed['income']=='<=50K',0,1)

adult_ed

,age,workclass,fnlwgt,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,income_target
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43,Private,222971,3,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico,<=50K,0
4996,31,Private,259425,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K,1
4997,47,Self-emp-inc,212120,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K,1
4998,31,Private,245880,9,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States,<=50K,0
4999,58,Local-gov,54947,10,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States,<=50K,0

In [38]:
adult_cat=adult_ed[['workclass','marital_status','occupation','relationship','race','sex','native_country']]
adult_no=adult_ed[['age','fnlwgt','education_num','capital_gain','capital_loss','hours_per_week']]
y=adult_ed['income_target']

In [39]:
df_cat_dum=pd.get_dummies(adult_cat,drop_first=True)

In [40]:

df_cat_dum

,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,marital_status_Married-AF-spouse,marital_status_Married-civ-spouse,marital_status_Married-spouse-absent,marital_status_Never-married,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4996,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4997,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4998,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4999,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [41]:
X=pd.concat([adult_no,df_cat_dum],axis=1)
X

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,50,83311,13,0,0,13,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,38,215646,9,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,53,234721,7,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,28,338409,13,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43,222971,3,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4996,31,259425,9,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4997,47,212120,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4998,31,245880,9,0,0,60,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4999,58,54947,10,0,0,55,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [42]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    1
4997    1
4998    0
4999    0
Name: income_target, Length: 5000, dtype: int32

In [43]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [44]:
X_scale

array([[ 0.03593442, -1.05821935,  1.16204955, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [ 0.84859611, -1.00347843,  1.16204955, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [-0.03794391,  0.24658891, -0.42328408, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       ...,
       [ 0.6269611 ,  0.21328149, -0.42328408, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [-0.55509226,  0.53218634, -0.42328408, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [ 1.43962278, -1.2714114 , -0.02695067, ...,  0.30985565,
        -0.04476615, -0.020004  ]])

In [45]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
X_scale=scx.fit_transform(X)

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X_scale, y, test_size=0.25, random_state=82)

In [47]:
log=LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
logis_y_pred=log.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,roc_auc_score,classification_report

In [50]:
print("logistics accuracy",accuracy_score(y_test,logis_y_pred))
print("roc_curve ",roc_auc_score(y_test,logis_y_pred))
print("confusion matrix",confusion_matrix(y_test,logis_y_pred))

logistics accuracy 0.836
roc_curve  0.7478571230752188
confusion matrix [[869  75]
 [130 176]]

In [51]:
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [52]:
dt_y_pred=dt.predict(X_test)


print("Decision accuracy",accuracy_score(y_test,dt_y_pred))
print("roc_curve ",roc_auc_score(y_test,dt_y_pred))
print("confusion matrix",confusion_matrix(y_test,dt_y_pred))

Decision accuracy 0.7896
roc_curve  0.7182411100033235
confusion matrix [[810 134]
 [129 177]]

In [53]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf_y_pred=dt.predict(X_test)


print("Rf Base accuracy",accuracy_score(y_test,rf_y_pred))
print("roc_curve ",roc_auc_score(y_test,rf_y_pred))
print("confusion matrix",confusion_matrix(y_test,rf_y_pred))

Rf Base accuracy 0.7896
roc_curve  0.7182411100033235
confusion matrix [[810 134]
 [129 177]]

In [65]:
from sklearn.model_selection import GridSearchCV
params={'n_estimators':[200,500,700,800],'max_depth':[10,15,18,20],'min_samples_leaf':[3,6,9]}
gscv=GridSearchCV(rf,params,verbose=3)

In [66]:
print(gscv.fit(X_train,y_train))

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.848, total=   0.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.7s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.844, total=   0.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.5s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.847, total=   0.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.848, total=   0.9s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.849, total=   0.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.851, total=   1.9s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.845, total=   2.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.843, total=   1.9s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.848, total=   1.9s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.851, total=   1.9s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.852, total=   2.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.848, total=   2.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.843, total=   2.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.848, total=   2.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.849, total=   2.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.851, total=   3.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.848, total=   3.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.843, total=   3.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.852, total=   3.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.851, total=   3.0s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.843, total=   0.7s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.849, total=   0.7s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.843, total=   0.7s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.841, total=   0.7s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.847, total=   0.7s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.852, total=   1.8s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.845, total=   1.8s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.847, total=   1.8s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.844, total=   1.8s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.844, total=   1.8s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.847, total=   2.5s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.848, total=   2.5s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.840, total=   2.5s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.844, total=   2.6s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.845, total=   2.6s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.849, total=   2.9s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.847, total=   2.9s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.843, total=   3.1s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.848, total=   3.0s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.848, total=   3.2s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.843, total=   0.8s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.849, total=   0.8s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.841, total=   0.7s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.837, total=   0.7s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.845, total=   0.7s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.845, total=   1.9s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.845, total=   1.9s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.841, total=   1.8s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.840, total=   1.8s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.848, total=   1.8s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.847, total=   2.5s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.844, total=   2.5s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.839, total=   2.5s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.840, total=   2.5s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.843, total=   2.5s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............

[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.843, total=   2.9s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.847, total=   2.9s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.841, total=   2.9s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.840, total=   2.8s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.843, total=   2.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.855, total=   0.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.848, total=   0.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.853, total=   0.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.853, total=   0.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.852, total=   2.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.848, total=   2.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.848, total=   2.1s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.851, total=   2.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.852, total=   2.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.851, total=   2.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.841, total=   2.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.851, total=   2.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.852, total=   3.2s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.852, total=   3.3s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.849, total=   3.7s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.848, total=   3.5s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.848, total=   3.4s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.855, total=   3.4s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.852, total=   3.4s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.848, total=   0.9s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.843, total=   0.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.847, total=   0.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.848, total=   2.1s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.851, total=   2.1s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.849, total=   2.2s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.847, total=   2.1s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.845, total=   2.2s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.847, total=   2.9s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.848, total=   2.9s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.844, total=   2.7s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.844, total=   2.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.851, total=   2.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.848, total=   3.3s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.849, total=   3.4s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.849, total=   3.4s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.851, total=   3.2s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.849, total=   3.2s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.848, total=   0.8s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.847, total=   0.7s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.841, total=   0.8s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.849, total=   0.8s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.851, total=   1.9s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.848, total=   2.0s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.844, total=   1.9s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............

[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.844, total=   1.9s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.845, total=   2.0s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.847, total=   2.8s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.848, total=   3.0s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.844, total=   3.1s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.844, total=   2.9s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.848, total=   3.2s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.847, total=   3.3s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.844, total=   3.3s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.844, total=   3.4s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.843, total=   3.5s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.849, total=   3.9s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.855, total=   1.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.847, total=   1.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.852, total=   1.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.849, total=   1.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.859, total=   1.1s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.852, total=   2.6s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.844, total=   2.7s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.849, total=   2.5s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.855, total=   2.6s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.851, total=   2.4s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.856, total=   3.5s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.847, total=   3.2s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.848, total=   2.9s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.855, total=   2.9s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.853, total=   3.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.855, total=   3.5s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.847, total=   3.4s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.851, total=   3.4s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.852, total=   3.4s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.853, total=   3.4s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.852, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.853, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.847, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.845, total=   2.0s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.851, total=   2.0s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.843, total=   2.0s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.851, total=   2.1s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.852, total=   2.1s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.849, total=   2.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.849, total=   2.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.851, total=   2.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.847, total=   2.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.852, total=   2.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.848, total=   3.4s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.847, total=   3.3s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.849, total=   3.3s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.847, total=   3.3s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.852, total=   3.3s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............

[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.848, total=   0.8s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.849, total=   0.8s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.848, total=   0.8s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.848, total=   2.0s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.848, total=   2.2s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.844, total=   2.0s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.845, total=   1.9s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.849, total=   1.9s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.847, total=   2.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.847, total=   2.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.845, total=   2.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.845, total=   2.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.849, total=   2.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.844, total=   3.1s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.851, total=   3.1s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.843, total=   3.2s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.843, total=   3.2s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.848, total=   3.3s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.851, total=   0.9s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.851, total=   0.9s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.853, total=   0.9s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.851, total=   0.9s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.849, total=   1.0s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.853, total=   2.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.847, total=   2.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.852, total=   2.3s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.852, total=   2.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.852, total=   2.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.853, total=   3.0s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.843, total=   3.0s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.847, total=   3.0s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.851, total=   3.1s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.853, total=   3.0s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.851, total=   3.5s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.845, total=   3.5s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.847, total=   3.5s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.852, total=   3.4s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.856, total=   3.4s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.849, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.847, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.845, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.848, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.849, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.849, total=   2.0s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.852, total=   2.0s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.852, total=   2.0s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.847, total=   2.0s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.849, total=   2.0s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.848, total=   2.9s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.848, total=   2.9s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.849, total=   2.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.848, total=   2.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............

[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.851, total=   2.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.848, total=   3.2s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.847, total=   3.2s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.845, total=   3.4s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.848, total=   3.3s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.853, total=   3.2s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.848, total=   0.8s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.844, total=   0.8s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.843, total=   0.8s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.843, total=   0.8s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.849, total=   0.8s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.848, total=   1.9s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.851, total=   1.9s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.845, total=   1.9s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.843, total=   1.9s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.849, total=   1.9s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.849, total=   2.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.849, total=   2.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.843, total=   2.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.847, total=   2.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.851, total=   2.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.848, total=   3.1s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.849, total=   3.2s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.844, total=   3.0s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.843, total=   3.1s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.848, total=   3.1s

[Parallel(n_jobs=1)]: Done 240 out of 240 | elapsed:  8.9min finished

GridSearchCV(cv=None, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': [10, 15, 18, 20],
                         'min_samples_leaf': [3, 6, 9],
                         'n_estimators': [200, 500, 700, 800]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [67]:
gscv.best_score_

0.8522666666666666

In [68]:
gscv.best_params_

{'max_depth': 18, 'min_samples_leaf': 3, 'n_estimators': 200}

In [69]:
gscv.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=18, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
rf_improve=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
rf_improve.fit(X_train,y_train)

In [ ]:
rf_improve.oob_score_

In [ ]:
imp_final_pred=rf_improve.predict(X_test)
print(accuracy_score(y_test,imp_final_pred))
print("Rf Imp accuracy",accuracy_score(y_test,imp_final_pred))
print("roc_curve ",roc_auc_score(y_test,imp_final_pred))
print("confusion matrix",confusion_matrix(y_test,imp_final_pred))

In [ ]:
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
knn_pred=knn.predict(X_test)

In [ ]:
print("KNN accuracy",accuracy_score(y_test,knn_pred))
print("roc_curve ",roc_auc_score(y_test,knn_pred))
print("confusion matrix",confusion_matrix(y_test,knn_pred))